# Generated by Django 3.2.7 on 2021-09-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0016_auto_20210422_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mame', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userProfile.profile')),
            ],
            options={
                'verbose_name': 'Emails',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
