# Generated by Django 3.2.7 on 2021-09-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0002_auto_20210914_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
