# Generated by Django 3.2.7 on 2021-10-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0016_auto_20210422_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watermark',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
