# Generated by Django 3.2.7 on 2021-09-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_order_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='finalPrice',
            field=models.FloatField(default=0),
        ),
    ]
